Added code to support IAM API Key Authentication
amankrsingh2000/loki pull request #7
Opened 2023-03-09 06:50 UTC by athira-varghese

https://github.ibm.com/Observability/dragonlog/issues/1352

2023-03-09 06:59 UTC, tareqmamari commented on pkg/storage/chunk/client/ibmcloud/cos_object_client.go
> +	if cfg.ApiKey.String() == "" {
If we don't have complete HMAC credentials or API Key we should raise an error that there must be at least one authentication method enabled.

2023-03-09 06:59 UTC, tareqmamari commented on pkg/storage/chunk/client/ibmcloud/cos_object_client.go
> +	if cfg.AuthEndpoint == "" {
This check is needed only if we use API Key authentication

2023-03-09 07:00 UTC, tareqmamari commented on pkg/storage/chunk/client/ibmcloud/cos_object_client.go
> +	if cfg.ServiceInstanceID == "" {
this one as well, we only need it if we use api key.

2023-03-09 11:52 UTC, Suruthi-G-K approved these changes

2023-03-09 12:40 UTC, shahulsonhal commented on pkg/storage/chunk/client/ibmcloud/cos_object_client.go
> +const DEFAULT_COS_AUTH_ENDPOINT = "https://iam.cloud.ibm.com/identity/token"
Is there any specific reason to capitalise the constant? Can't we follow the normal go variable convention here? Since in Go the things are exported if it's start with a capital letter. 
```suggestion
const defaultCOSAuthEndpoint = "https://iam.cloud.ibm.com/identity/token"
```

2023-03-09 13:00 UTC, adityacs commented on pkg/storage/chunk/client/ibmcloud/cos_object_client.go
> +const DEFAULT_COS_AUTH_ENDPOINT = "https://iam.cloud.ibm.com/identity/token"
The general convention is to capitalize the constants. Agree on the const being exported but don't have a strong argument whether it should be exported or not in this case.

2023-03-10 12:28 UTC, shahulsonhal requested changes
@amankrsingh2000 It seems like there is an indentation (formatting) issue in your last commit. It should be auto formatted when you save the file (it wont work if you have turned on auto saving in your editor). Could you please check?

2023-03-10 19:41 UTC, tareqmamari commented on pkg/storage/chunk/client/ibmcloud/cos_object_client.go
> +const DEFAULT_COS_AUTH_ENDPOINT = "https://iam.cloud.ibm.com/identity/token"
Let's be consistent with what is already in Loki.

2023-03-10 19:42 UTC, tareqmamari commented
I am merging this PR, if any further changes are needed, please feel free to open another one.

2023-03-10 19:42 UTC, merged